from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

index_replacements = {
    "part-6-embodied-perception/module-27-visual-perception-for-action/index.html": (
        '<section class="production-depth-expansion"><h2>Instructor And Builder Notes</h2><p>Use this chapter as a complete teaching unit: concept, minimal implementation, library shortcut, diagnostic perturbation, and postmortem. The pattern prevents a perception model from being evaluated in isolation and never tested as part of the agent loop.</p><div class="comparison-table"><div class="comparison-table-title">Chapter Tool Map</div><table><thead><tr><th>Tool or Library</th><th>Where It Pays Off</th></tr></thead><tbody><tr><td>OpenCV</td><td>Use when it shortens the path from mechanism to reproducible embodied evidence.</td></tr><tr><td>PyTorch</td><td>Use when it shortens the path from mechanism to reproducible embodied evidence.</td></tr><tr><td>Segment Anything</td><td>Use when it shortens the path from mechanism to reproducible embodied evidence.</td></tr><tr><td>DINOv2</td><td>Use when it shortens the path from mechanism to reproducible embodied evidence.</td></tr><tr><td>Detectron2</td><td>Use when it shortens the path from mechanism to reproducible embodied evidence.</td></tr><tr><td>Ultralytics</td><td>Use when it shortens the path from mechanism to reproducible embodied evidence.</td></tr><tr><td>ROS 2 image pipelines</td><td>Use when it shortens the path from mechanism to reproducible embodied evidence.</td></tr></tbody></table></div><div class="callout self-check"><div class="callout-title">Readiness Check</div><p>Before leaving the chapter, the reader should be able to state one theory claim, one implementation claim, one evaluation claim, and one realistic failure mode.</p></div><div class="callout key-takeaway"><div class="callout-title">Teaching Takeaway</div><p>A strong chapter session ends with an artifact: a script, trace, simulator run, data card, map, or reproducible evaluation panel.</p></div></section>',
        '<section class="production-depth-expansion"><h2>Instructor And Builder Notes</h2><p>Use this chapter as a complete teaching unit for vision that changes robot behavior: calibration, masks, depth, motion, affordances, active sensing, and failure attribution. The through-line is a repeatable perception-to-action evidence record, so no detector, depth model, or tracker is evaluated apart from the command it changes.</p><div class="comparison-table"><div class="comparison-table-title">Chapter Tool Map</div><table><thead><tr><th>Tool or Library</th><th>Where It Pays Off</th></tr></thead><tbody><tr><td>OpenCV</td><td>Camera calibration, solvePnP, stereo geometry, optical flow, and quick image diagnostics.</td></tr><tr><td>PyTorch</td><td>Learned perception heads, uncertainty models, affordance maps, and batched visual features.</td></tr><tr><td>SAM 2 and Segment Anything workflows</td><td>Promptable masks, video object memory, interactive data creation, and region proposals.</td></tr><tr><td>DINOv2 and visual foundation features</td><td>Reusable descriptors for matching, segmentation support, object memory, and downstream robot perception.</td></tr><tr><td>Detectron2 or Ultralytics</td><td>Fast object proposals when boxes or instance masks are enough to seed action logic.</td></tr><tr><td>ROS 2 image pipelines</td><td>Timestamped image transport, diagnostics, replay, and message contracts for closed-loop systems.</td></tr></tbody></table></div><div class="callout self-check"><div class="callout-title">Readiness Check</div><p>Before leaving the chapter, the reader should be able to state the visual evidence, frame transform, uncertainty field, latency budget, chosen action, and failure label for every perception module.</p></div><div class="callout key-takeaway"><div class="callout-title">Teaching Takeaway</div><p>A strong chapter session ends with an action audit: the reader can show exactly how a visual estimate changed a robot command and how the decision would be replayed after a failure.</p></div></section>',
    ),
    "part-6-embodied-perception/module-28-3d-perception-and-neural-scene-representations/index.html": (
        '<section class="production-depth-expansion"><h2>Instructor And Builder Notes</h2><p>Use this chapter as a complete teaching unit: concept, minimal implementation, library shortcut, diagnostic perturbation, and postmortem. The pattern prevents a perception model from being evaluated in isolation and never tested as part of the agent loop.</p><div class="comparison-table"><div class="comparison-table-title">Chapter Tool Map</div><table><thead><tr><th>Tool or Library</th><th>Where It Pays Off</th></tr></thead><tbody><tr><td>Open3D</td><td>Use when it shortens the path from mechanism to reproducible embodied evidence.</td></tr><tr><td>PyTorch</td><td>Use when it shortens the path from mechanism to reproducible embodied evidence.</td></tr><tr><td>OpenCV</td><td>Use when it shortens the path from mechanism to reproducible embodied evidence.</td></tr><tr><td>Gaussian Splatting workflows</td><td>Use when it shortens the path from mechanism to reproducible embodied evidence.</td></tr><tr><td>Nerfstudio</td><td>Use when it shortens the path from mechanism to reproducible embodied evidence.</td></tr><tr><td>ROS 2</td><td>Use when it shortens the path from mechanism to reproducible embodied evidence.</td></tr><tr><td>Habitat-style simulators</td><td>Use when it shortens the path from mechanism to reproducible embodied evidence.</td></tr></tbody></table></div><div class="callout self-check"><div class="callout-title">Readiness Check</div><p>Before leaving the chapter, the reader should be able to state one theory claim, one implementation claim, one evaluation claim, and one realistic failure mode.</p></div><div class="callout key-takeaway"><div class="callout-title">Teaching Takeaway</div><p>A strong chapter session ends with an artifact: a script, trace, simulator run, data card, map, or reproducible evaluation panel.</p></div></section>',
        '<section class="production-depth-expansion"><h2>Instructor And Builder Notes</h2><p>Use this chapter as a complete teaching unit for scene memory that a robot can query: point clouds, object states, occupancy, neural fields, Gaussian splats, SLAM layers, and real2sim exports. The central question is which representation can answer the action query safely, not which representation renders the most impressive image.</p><div class="comparison-table"><div class="comparison-table-title">Chapter Tool Map</div><table><thead><tr><th>Tool or Library</th><th>Where It Pays Off</th></tr></thead><tbody><tr><td>Open3D</td><td>RGB-D conversion, point clouds, voxelization, registration, normals, and geometry inspection.</td></tr><tr><td>OpenCV</td><td>Camera intrinsics, stereo reconstruction, pose estimation, and calibration checks before 3D fusion.</td></tr><tr><td>PyTorch</td><td>Learned scene encoders, neural field components, uncertainty heads, and differentiable geometry prototypes.</td></tr><tr><td>Nerfstudio</td><td>NeRF and Splatfacto workflows for neural scene training, inspection, and export experiments.</td></tr><tr><td>gsplat and 3DGS workflows</td><td>CUDA-accelerated Gaussian splat rendering and explicit scene-element experimentation.</td></tr><tr><td>ROS 2 and SLAM stacks</td><td>Pose tracking, map publication, diagnostics, replay, and integration with navigation or manipulation.</td></tr></tbody></table></div><div class="callout self-check"><div class="callout-title">Readiness Check</div><p>Before leaving the chapter, the reader should be able to choose a representation for localization, collision checking, contact planning, visual replay, object reasoning, and simulation export.</p></div><div class="callout key-takeaway"><div class="callout-title">Teaching Takeaway</div><p>A strong chapter session ends with a query map: every scene representation is tied to the robot query it can answer and the safety checks it cannot replace.</p></div></section>',
    ),
}

figure_replacements = {
    "27.1": ("Scene shows a robot comparing an image label with a reachable action boundary, emphasizing that visual recognition must change a safe robot command.", "The useful question is not what the camera can name; it is which action becomes safe enough to execute."),
    "27.2": ("Scene shows a robot following a segmented object region through video while checking clearance before reaching, connecting masks to action-safe regions.", "A mask earns trust only after it stays trackable, metric, and safe enough for the next skill."),
    "27.3": ("Scene shows depth rays leaving a calibrated camera and landing on a tabletop object, turning pixels into metric clearance for a robot hand.", "Depth becomes robotics evidence when pixels, intrinsics, scale, and clearance all agree."),
    "27.4": ("Scene shows image motion arrows splitting into camera motion and object motion before a robot slows down near a moving obstacle.", "Flow is a control signal only after ego-motion and object motion stop pretending to be the same thing."),
    "27.5": ("Scene shows several candidate contact regions on an object, with one region rejected by reach and collision constraints before grasping.", "An affordance is a possibility, not a permission slip; the robot still has to reach it safely."),
    "28.1": ("Scene shows a robot comparing a flat camera view with a spatial map of reachable surfaces, free space, and hidden obstacles.", "3D matters because bodies need places to fit, surfaces to touch, and unknown space to respect."),
    "28.2": ("Scene shows depth pixels lifting into a sparse cloud of metric points that a robot can filter, transform, and query.", "A point cloud is useful when every dot carries units, frame, timestamp, and a reason to exist."),
    "28.3": ("Scene shows multiple camera views merging into persistent object poses and relations that survive as a robot moves around a room.", "Scene reconstruction is object memory with geometry, uncertainty, and a replay trail."),
    "28.4": ("Scene shows sensor rays carving free cells, occupied cells, and unknown space in a voxel map before a robot plans a path.", "Unknown is not free; a map is honest only when it remembers what it has not seen."),
    "28.5": ("Scene shows camera rays sampling a continuous neural field while a robot keeps a separate conservative geometry layer for motion.", "A beautiful render is not a collision certificate."),
}


for rel, (old, new) in index_replacements.items():
    path = ROOT / rel
    text = path.read_text(encoding="utf-8")
    if old in text:
        path.write_text(text.replace(old, new), encoding="utf-8", newline="\n")


for section, (alt, caption) in figure_replacements.items():
    chapter = "module-27-visual-perception-for-action" if section.startswith("27.") else "module-28-3d-perception-and-neural-scene-representations"
    path = ROOT / "part-6-embodied-perception" / chapter / f"section-{section}.html"
    text = path.read_text(encoding="utf-8")
    start = text.find('<figure class="illustration">')
    if start == -1:
        continue
    end = text.find("</figure>", start) + len("</figure>")
    block = text[start:end]
    src_start = block.find('src="')
    src_end = block.find('"', src_start + 5)
    src = block[src_start + 5:src_end]
    new_block = (
        '<figure class="illustration">\n'
        f'<img alt="{alt}" loading="lazy" src="{src}"/>\n'
        f'<figcaption><strong>Figure {section}A</strong>: {caption}</figcaption>\n'
        '</figure>'
    )
    path.write_text(text[:start] + new_block + text[end:], encoding="utf-8", newline="\n")
